### ISSUE TITLE
Periodically release offline HTML export

### ISSUE THREAD

**Issue by gd4c** [factbook/factbook.github.io#3]
Through GitHub releases, instead of people scraping https://factbook.github.io/, you could provide an offline (HTML with only localized links and scripts) release once every 6-12 months for that purpose.

What do you think?

**Comment by geraldb** [comment]
sorry no time and budget. you can get updated factbook.json datasets here -> https://github.com/factbook/factbook.json

**Comment by gd4c** [comment]
I understand. No problem.

**Comment by geraldb** [comment]
@gd4c  fyi:  the fix is to help with the budget than happy to update.
